{% set name = "swmmanywhere" %}
{% set version = "0.1.16" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/swmmanywhere-{{ version }}.tar.gz
  sha256: 4e94ef65c514ccda7b0d5a6c626c48c314060b2eee77b786ebda1bff876c5b7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - cdsapi
    - cytoolz
    - geopandas >=1
    - geopy
    - joblib
    - jsonschema
    - loguru
    - matplotlib-base
    - netcdf4
    - networkx >=3
    - numpy >=2
    - osmnx >=1.9.3
    - pandas
    - planetary-computer
    - pyarrow
    - pydantic
    - pyflwdir
    - pystac-client
    - pyswmm
    - pywbt >=0.2.4
    - pyyaml
    - rasterio
    - rioxarray
    - scipy
    - shapely
    - tqdm
    - xarray

test:
  imports:
    - swmmanywhere
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: SWMManywhere software
  home: https://github.com/ImperialCollegeLondon/SWMManywhere
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - src/netcomp/LICENSE.txt

extra:
  recipe-maintainers:
    - dalonsoa
    - barneydobson
    - cheginit
